# Generated by Django 3.2.4 on 2021-06-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='Marca',
            new_name='marca',
        ),
    ]
